# Generated by Django 5.0.1 on 2024-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactmessage_alter_imageproduit_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
