# Generated by Django 5.0.1 on 2024-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantityProducts',
            field=models.IntegerField(default=1),
        ),
    ]
